#--##
#--##   SET UP DATABASE
#--####################################### 
DROP DATABASE IF EXISTS pyKeyLog;
CREATE DATABASE pyKeyLog;
USE pyKeyLog;


#--##
#--##   CREATE TABLES
#--####################################### 
CREATE TABLE LogSession(
  AID         INTEGER(11)   PRIMARY KEY AUTO_INCREMENT,
	UNAME				VARCHAR(128)	NOT NULL,
	TIMESTAMP		TIMESTAMP			NOT NULL
)ENGINE InnoDB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE Submit(
  AID         INTEGER(11)   PRIMARY KEY AUTO_INCREMENT,
	SID					INTEGER(11)		NOT NULL,
	ANSWER			TEXT					NOT NULL,
	SUBMIT			TEXT					NOT NULL
)ENGINE InnoDB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE KeyLog(
  AID         INTEGER(11)   PRIMARY KEY AUTO_INCREMENT,
	SID					INTEGER(11)		NOT NULL,
	REL					INTEGER(11)		NULL DEFAULT NULL,
	TIME				INTEGER(11)		NOT NULL,
	EVENT				INTEGER(1)		NOT NULL DEFAULT 0,
	SCANCODE		INTEGER(11)		NOT NULL,
	ASCII				INTEGER(11)		NOT NULL,
	TITLE				VARCHAR(100)	NOT NULL
)ENGINE InnoDB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


